### ISSUE TITLE
Syntax error : Use of const in strict mode

### ISSUE THREAD

**Issue by lowly2005** [webpack-contrib/style-loader#180]
Getting this error when trying to deploy my app on heroku.

56% 265/339 build modules/tmp/build_e583c980a208f2d132f008b26720559f/XXXXX-1099378b2f8347e19843b2c8c003bfb7de427f2c/node_modules/style-loader/node_modules/loader-utils/lib/index.js:3
       const getOptions = require("./getOptions");
       ^^^^^
       SyntaxError: Use of const in strict mode.
       at exports.runInThisContext (vm.js:73:16)
       at Module._compile (module.js:443:25)
       at Object.Module._extensions..js (module.js:478:10)
       at Module.load (module.js:355:32)
       at Function.Module._load (module.js:310:12)
       at Module.require (module.js:365:17)
       at require (module.js:384:17)

Thanks,

**Comment by lowly2005** [comment]
Just upgraded the node version

**Comment by ramusus** [comment]
@lowly2005 Did you solve this issue by simple upgrading node version?

**Comment by lowly2005** [comment]
@ramusus  yes
