### ISSUE TITLE
Deprecation warning with valid options

### ISSUE THREAD

**Issue by Whoaa512** [webpack-contrib/style-loader#318]
Running my webpack build with `process.traceDeprecation = true` and I get this

```
(node:25748) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
    at Object.parseQuery (/home/code/node_modules/style-loader/node_modules/loader-utils/index.js:78:3)
    at Object.module.exports.pitch (/home/code/node_modules/style-loader/index.js:10:26)
    at LOADER_EXECUTION (/home/code/node_modules/loader-runner/lib/LoaderRunner.js:119:14)
    at runSyncOrAsync (/home/code/node_modules/loader-runner/lib/LoaderRunner.js:120:4)
    at /home/code/node_modules/loader-runner/lib/LoaderRunner.js:175:3
    at loadLoader (/home/code/node_modules/loader-runner/lib/loadLoader.js:36:3)
    at iteratePitchingLoaders (/home/code/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at runLoaders (/home/code/node_modules/loader-runner/lib/LoaderRunner.js:362:2)
    at NormalModule.doBuild (/home/code/node_modules/webpack/lib/NormalModule.js:227:3)
    at NormalModule.build (/home/code/node_modules/webpack/lib/NormalModule.js:345:15)
    at Compilation.buildModule (/home/code/node_modules/webpack/lib/Compilation.js:362:10)
    at factory.create (/home/code/node_modules/webpack/lib/Compilation.js:583:14)
    at factory (/home/code/node_modules/webpack/lib/NormalModuleFactory.js:366:6)
    at hooks.afterResolve.callAsync (/home/code/node_modules/webpack/lib/NormalModuleFactory.js:143:13)
    at AsyncSeriesWaterfallHook.eval [as callAsync] (eval at create (/home/code/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
    at resolver (/home/code/node_modules/webpack/lib/NormalModuleFactory.js:126:29)
    at process.nextTick (/home/code/node_modules/webpack/lib/NormalModuleFactory.js:304:9)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

My style loader config looks like this

```javascript
const styleLoader = {
	loader: 'style-loader',
	options: { sourceMap: !disableSourceMaps },
}
```

When I change my config to this it goes away:
```javascript
const styleLoader = {
    loader: `style-loader?sourceMap=${!disableSourceMaps}`,
    // options: { sourceMap: !disableSourceMaps },
}
```

**Comment by Whoaa512** [comment]
My bad, didn't update to latest version.
