### ISSUE TITLE
ReferenceError: document is not defined

### ISSUE THREAD

**Issue by teamco** [webpack-contrib/style-loader#433]
- Operating System: MacOs Catalina
- Node Version: 13.x
- webpack Version: 4.2
- style-loader Version: 1.0.1

Some strange error during build:
`Entrypoint main = main.js main.js.map
[0] multi webpack-hot-middleware/client?path=/__webpack_hmr&timeout=20000 
...
[./node_modules/webpack-hot-middleware/client.js?path=/__webpack_hmr&timeout=20000] (webpack)-hot-middleware/client.js?path=/__webpack_hmr&timeout=20000 7.68 KiB {main} [built]
[./node_modules/webpack-hot-middleware/process-update.js] (webpack)-hot-middleware/process-update.js 4.35 KiB {main} [built]
[./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {main} [built]
    + 1247 hidden modules
Child HtmlWebpackCompiler:
     1 asset
    Entrypoint HtmlWebpackPlugin_0 = __child-HtmlWebpackPlugin_0
    [./node_modules/html-webpack-plugin/lib/loader.js!./app/javascript/packs/html/index.html] 880 bytes {HtmlWebpackPlugin_0} [built]
/Users/<user>/<app>/dist/main.js:119438
  var style = document.createElement('style');
              ^

ReferenceError: document is not defined
    at insertStyleElement (/Users/<user>/<app>/dist/main.js:119438:15)
    at addStyle (/Users/<user>/<app>/dist/main.js:119550:13)
    at addStylesToDom (/Users/<user>/<app>/dist/main.js:119425:20)
    at ./node_modules/style-loader/dist/runtime/injectStylesIntoStyleTag.js.module.exports (/Users/<user>/<app>/dist/main.js:119582:3)
    at Object../app/javascript/packs/scss/jquery-ui.min.scss (/Users/<user>/<app>/dist/main.js:47477:191)
    at __webpack_require__ (/Users/<user>/<app>/dist/main.js:737:30)
    at fn (/Users/<user>/<app>/dist/main.js:111:20)
    at Module../app/javascript/packs/development.js (/Users/<user>/<app>/dist/main.js:17663:82)
    at __webpack_require__ (/Users/<user>/<app>/dist/main.js:737:30)
    at fn (/Users/<user>/<app>/dist/main.js:111:20)
`
Please help

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted issue template. It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
