### ISSUE TITLE
ReferenceError: document is not defined

### ISSUE THREAD

**Issue by teamco** [webpack-contrib/style-loader#439]
- Operating System: MacOs Catalina
- Node Version: 13.3.0
- NPM Version: 6.13.2
- webpack Version: 4.41.2
- style-loader Version: 1.0.1

### Expected Behavior
Successfully compiled code

### Actual Behavior
ReferenceError: document is not defined

### Code

```js
Entrypoint main = main.js main.js.map
[0] multi webpack-hot-middleware/client?path=/__webpack_hmr&timeout=20000 
...
[./node_modules/webpack-hot-middleware/client.js?path=/__webpack_hmr&timeout=20000] (webpack)-hot-middleware/client.js?path=/__webpack_hmr&timeout=20000 7.68 KiB {main} [built]
[./node_modules/webpack-hot-middleware/process-update.js] (webpack)-hot-middleware/process-update.js 4.35 KiB {main} [built]
[./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {main} [built]
   + 1247 hidden modules
Child HtmlWebpackCompiler:
      1 asset
Entrypoint HtmlWebpackPlugin_0 = __child-HtmlWebpackPlugin_0
[./node_modules/html-webpack-plugin/lib/loader.js!./app/javascript/packs/html/index.html] 880 bytes {HtmlWebpackPlugin_0} [built]
/Users/<user>/<app>/dist/main.js:119438
```

```js
var style = document.createElement('style');
		              ^
**ReferenceError: document is not defined**
   at insertStyleElement (/Users/<user>/<app>/dist/main.js:119438:15)
   at addStyle (/Users/<user>/<app>/dist/main.js:119550:13)
   at addStylesToDom (/Users/<user>/<app>/dist/main.js:119425:20)
   at ./node_modules/style-loader/dist/runtime/injectStylesIntoStyleTag.js.module.exports (/Users/<user>/<app>/dist/main.js:119582:3)
   at Object../app/javascript/packs/scss/jquery-ui.min.scss (/Users/<user>/<app>/dist/main.js:47477:191)
   at __webpack_require__ (/Users/<user>/<app>/dist/main.js:737:30)
   at fn (/Users/<user>/<app>/dist/main.js:111:20)
   at Module../app/javascript/packs/development.js (/Users/<user>/<app>/dist/main.js:17663:82)
   at __webpack_require__ (/Users/<user>/<app>/dist/main.js:737:30)
   at fn (/Users/<user>/<app>/dist/main.js:111:20)
```

### How Do We Reproduce?
**package.json** script
webpack --mode development --config webpack.server.config.js && webpack --mode development --config webpack.dev.config.js  && node ./dist/main.js

Here is **gist**:
**webpack.server.config.js**
https://gist.github.com/teamco/2dabcc2a3cbb9155c94c942a4f33f116
**webpack.dev.config.js**
https://gist.github.com/teamco/8ec5b0e72902bf25310476fa558ec65c

**Comment by evilebottnawi** [comment]
Don't use style-loader in environment where document is unavailable
